#!/usr/bin/python3

from sys import argv

def factorize(value):
    """"print an integer > 1  primary descomposition"""
    a = 2

    if value < 2:
        return
    while value % a:
        a += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / a, a))

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.split()[0])
            factorize(value)
            line = file.readline()
except:
    pass
